using UnityEngine;
using System.Collections.Generic;

// handler class for the collection of game objects/meshes generated by their tile location

public class Meshes
{
    private Dictionary<Coord, List<GameObject>> meshesDict = new Dictionary<Coord, List<GameObject>>();

    public List<GameObject> Get(Coord coord)
    {
        List<GameObject> meshes;
        if(meshesDict.TryGetValue(coord, out meshes))
            return meshes;
        else
            return null;
    }

    public void Put(Coord coord, List<GameObject> meshes)
    {
        // overwrite old data here
        Remove(coord);
        meshesDict.Add(coord, meshes);
    }

    public void Remove(Coord coord)
    {
        List<GameObject> meshes = Get(coord);
        if(meshes != null)
        {
            meshesDict.Remove(coord);
            foreach(GameObject mesh in meshes)
                MonoBehaviour.Destroy(mesh);
        }
    }
}
