using UnityEngine;
using System.Collections.Generic;

// handler class for the collection of game objects/textures generated by their tile location

public class TileMaterials
{
    private Dictionary<Coord, Material> TheTileMaterials = new Dictionary<Coord, Material>();
    private _WorldSpace TheWorldSpace;

    public TileMaterials(_WorldSpace TheWorldSpace)
    {
        this.TheWorldSpace = TheWorldSpace;
    }

    public Material Get(Coord coord)
    {
        Material TileMaterial;
        if(TheTileMaterials.TryGetValue(coord, out TileMaterial))
            return TileMaterial;
        else
        {
            Texture2D TileTexture = new Texture2D(TheWorldSpace.TileTextureWidth, TheWorldSpace.TileTextureHeight);
            for(int y = 0; y < TheWorldSpace.TileTextureHeight; y++)
                for(int x = 0; x < TheWorldSpace.TileTextureWidth; x++)
                    TileTexture.SetPixel(x, y, TheWorldSpace.TileTextureSheet.GetPixel((coord.x*TheWorldSpace.TileTextureWidth)+x, (coord.y*TheWorldSpace.TileTextureHeight)+y));
            TileTexture.wrapMode = TextureWrapMode.Repeat;
            TileTexture.filterMode = FilterMode.Point;
            TileTexture.Apply();

            TileMaterial = new Material(Shader.Find("Standard"));
            TileMaterial.SetTexture("_MainTex", TileTexture);
            TileMaterial.SetFloat("_Glossiness", 0);
            TileMaterial.SetFloat("_Metallic", 0);
            TileMaterial.name = coord.x + ", " + coord.y;

            TheTileMaterials.Add(coord, TileMaterial);
            return TileMaterial;
        }
    }
}
